# Generated by Django 5.0.1 on 2026-01-16 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Request body or query params')),
                ('expected_status', models.IntegerField(default=200)),
                ('is_generated', models.BooleanField(default=False)),
                ('user_feedback', models.TextField(blank=True, help_text='History of user comments/refinements', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, help_text='AI Generated Summary of the run', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passed', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.testcase')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.testrun')),
            ],
        ),
    ]
