# Generated by Django 6.0.1 on 2026-01-16 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testcase_testrun_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Groq', 'Gemini Pro'", max_length=100)),
                ('provider_type', models.CharField(choices=[('GEMINI', 'Google Gemini'), ('OPENAI', 'OpenAI Compatible (Groq, AIPipe, etc.)')], default='OPENAI', max_length=50)),
                ('base_url', models.CharField(blank=True, help_text='Required for OpenAI compatible providers (e.g. https://api.groq.com/openai/v1)', max_length=500, null=True)),
                ('api_key', models.CharField(help_text='Store securely. For MVP, plain text.', max_length=500)),
                ('default_model', models.CharField(help_text='Model ID to use (e.g. gpt-4o, llama3-70b-8192)', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only one provider should be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
