# Generated by Django 5.0.1 on 2026-01-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_llmprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
