# Generated by Django 6.0.1 on 2026-01-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='provider_type',
            field=models.CharField(choices=[('GEMINI', 'Google Gemini'), ('OPENAI', 'OpenAI Compatible (Groq, AIPipe, etc.)'), ('OLLAMA', 'Ollama (Local)')], default='OPENAI', max_length=50),
        ),
    ]
