# Generated by Django 6.0.1 on 2026-01-27 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_tests', models.IntegerField(default=0, help_text='Total number of tests to execute')),
                ('completed_tests', models.IntegerField(default=0, help_text='Number of tests completed so far')),
                ('passed_tests', models.IntegerField(default=0, help_text='Number of tests that passed')),
                ('failed_tests', models.IntegerField(default=0, help_text='Number of tests that failed')),
                ('parallel', models.BooleanField(default=False, help_text='Whether to run tests in parallel')),
                ('max_workers', models.IntegerField(default=5, help_text='Maximum number of parallel workers')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(default='system', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_runs', to='core.project')),
            ],
        ),
    ]
