# Generated by Django 6.0.1 on 2026-01-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bulktestrun'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['executed_at'], name='testresult_executed_at_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['test_run', 'status'], name='testresult_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['test_case', 'status', 'executed_at'], name='testresult_flaky_idx'),
        ),
    ]
