# Generated by Django 6.0.1 on 2026-01-28 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_testresult_testresult_executed_at_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='data_row_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='bulktestrun',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_runs', to='core.collection'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='core.collection'),
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='test_data/%Y/%m/%d/')),
                ('file_type', models.CharField(default='csv', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.testdata'),
        ),
    ]
