# Generated by Django 6.0.1 on 2026-02-04 17:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testresult_data_row_index_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='api_key',
            field=core.fields.EncryptedCharField(help_text='Stored securely using Fernet encryption.', max_length=500),
        ),
    ]
