# Generated by Django 6.0.1 on 2026-02-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_llmprovider_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='parameters',
            field=models.JSONField(blank=True, default=list, help_text='Query parameters'),
        ),
    ]
